#!/usr/bin/env bash
# check-workspace-versions.test.sh — fixture harness for the workspace-version gate.
#
# This harness is authored WITHOUT invoking Cargo. When EXECUTED it drives
# scripts/check-workspace-versions.sh against hand-built temporary workspaces
# (no external dependencies, so their Cargo.lock is trivially consistent and
# `cargo metadata --locked` accepts them) plus the real repository.
#
# It proves the gate:
#   * FAILS (nonzero, business assertion) on a manifest/lock version drift,
#   * FAILS on a workspace package-set mismatch,
#   * FAILS on a stale version.txt,
#   * FAILS on a stale .release-please-manifest.json,
#   * PASSES (zero) on the real repository lock,
# and on EVERY scenario the fixture's Cargo.lock bytes are byte-for-byte
# unchanged.
#
# Ordering contract: the very first Cargo invocation of the whole task must be
# the gate run against the REAL repository. This harness must therefore only be
# executed AFTER that first real gate run. It runs cargo (via the gate) on each
# fixture, which are all later invocations.
#
# Usage: scripts/tests/check-workspace-versions.test.sh

set -euo pipefail

HARNESS_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd -- "$HARNESS_DIR/../.." && pwd -P)"
GATE="$REPO_ROOT/scripts/check-workspace-versions.sh"
V="0.40.4"

[ -x "$GATE" ] || { printf 'harness: gate not executable: %s\n' "$GATE" >&2; exit 2; }

WORK="$(mktemp -d)"
cleanup() { rm -rf "$WORK"; }
trap cleanup EXIT

PASS=0
FAIL=0
note()  { printf '  %s\n' "$1"; }
ok()    { printf 'PASS: %s\n' "$1"; PASS=$((PASS + 1)); }
bad()   { printf 'FAIL: %s\n' "$1" >&2; FAIL=$((FAIL + 1)); }

# ---------------------------------------------------------------------------
# make_base_workspace DIR VERSION
#   Writes a minimal, dependency-free two-member workspace whose Cargo.lock is
#   consistent with its manifests. All four version surfaces are set to VERSION.
# ---------------------------------------------------------------------------
make_base_workspace() {
    local dir="$1" ver="$2"
    mkdir -p "$dir/pa/src" "$dir/pb/src"

    cat > "$dir/Cargo.toml" <<EOF
[workspace]
members = ["pa", "pb"]
resolver = "2"

[workspace.package]
version = "$ver"
EOF

    cat > "$dir/pa/Cargo.toml" <<'EOF'
[package]
name = "fixture-pa"
version.workspace = true
edition = "2021"
EOF
    printf '// fixture\n' > "$dir/pa/src/lib.rs"

    cat > "$dir/pb/Cargo.toml" <<'EOF'
[package]
name = "fixture-pb"
version.workspace = true
edition = "2021"
EOF
    printf '// fixture\n' > "$dir/pb/src/lib.rs"

    cat > "$dir/Cargo.lock" <<EOF
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "fixture-pa"
version = "$ver"

[[package]]
name = "fixture-pb"
version = "$ver"
EOF

    printf '%s\n' "$ver" > "$dir/version.txt"
    printf '{\n  ".": "%s"\n}\n' "$ver" > "$dir/.release-please-manifest.json"
}

# ---------------------------------------------------------------------------
# run_scenario NAME DIR EXPECT_EXIT EXPECT_STDERR_REGEX
#   Snapshots the fixture lock, runs the gate, asserts exit code, asserts the
#   expected diagnostic appears (business assertion — not a compile/setup
#   error), and asserts the lock bytes are unchanged.
# ---------------------------------------------------------------------------
run_scenario() {
    local name="$1" dir="$2" expect_exit="$3" expect_re="$4"
    local pre post rc out err
    pre="$(sha256sum "$dir/Cargo.lock" | awk '{print $1}')"
    out="$WORK/$name.out"; err="$WORK/$name.err"
    set +e
    "$GATE" "$dir" >"$out" 2>"$err"
    rc=$?
    set -e
    post="$(sha256sum "$dir/Cargo.lock" | awk '{print $1}')"

    local scenario_ok=1
    if [ "$rc" -ne "$expect_exit" ]; then
        bad "$name: expected exit $expect_exit, got $rc"
        note "stderr: $(tr '\n' '|' < "$err")"
        scenario_ok=0
    fi
    if [ -n "$expect_re" ]; then
        if ! grep -Eq "$expect_re" "$err" "$out"; then
            bad "$name: expected diagnostic /$expect_re/ not found"
            note "stderr: $(tr '\n' '|' < "$err")"
            scenario_ok=0
        fi
    fi
    if [ "$pre" != "$post" ]; then
        bad "$name: Cargo.lock MUTATED (pre=$pre post=$post)"
        scenario_ok=0
    fi
    if [ "$scenario_ok" -eq 1 ]; then
        ok "$name (exit=$rc, lock unchanged: ${pre:0:12}…)"
    fi
}

printf '=== workspace-version gate fixture harness ===\n'

# Scenario A — manifest 0.40.4 / lock 0.40.3 drift.
DIR_A="$WORK/drift"
make_base_workspace "$DIR_A" "$V"
# Rewrite ONLY the lock member versions to 0.40.3 (manifests stay 0.40.4).
sed -i 's/^version = "0.40.4"$/version = "0.40.3"/' "$DIR_A/Cargo.lock"
run_scenario "A_manifest_lock_drift" "$DIR_A" 1 "out of date|MISMATCH|0\.40\.3"

# Scenario B — package-set mismatch: a source-less vendored crate exists in the
# lock and is a path dependency of pa, but is NOT a workspace member, so
# `cargo metadata --no-deps` omits it while the lock lists it.
DIR_B="$WORK/pkgset"
make_base_workspace "$DIR_B" "$V"
mkdir -p "$DIR_B/vendored/src"
cat > "$DIR_B/vendored/Cargo.toml" <<EOF
[package]
name = "fixture-vendored"
version = "$V"
edition = "2021"
EOF
printf '// fixture\n' > "$DIR_B/vendored/src/lib.rs"
cat > "$DIR_B/pa/Cargo.toml" <<'EOF'
[package]
name = "fixture-pa"
version.workspace = true
edition = "2021"

[dependencies]
fixture-vendored = { path = "../vendored" }
EOF
cat > "$DIR_B/Cargo.lock" <<EOF
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "fixture-pa"
version = "$V"
dependencies = [
 "fixture-vendored",
]

[[package]]
name = "fixture-pb"
version = "$V"

[[package]]
name = "fixture-vendored"
version = "$V"
EOF
run_scenario "B_package_set_mismatch" "$DIR_B" 1 "package set differs|fixture-vendored"

# Scenario C — stale version.txt (all else valid).
DIR_C="$WORK/stale_version_txt"
make_base_workspace "$DIR_C" "$V"
printf '0.40.3\n' > "$DIR_C/version.txt"
run_scenario "C_stale_version_txt" "$DIR_C" 1 "version\.txt"

# Scenario D — stale release-please manifest (all else valid).
DIR_D="$WORK/stale_release_manifest"
make_base_workspace "$DIR_D" "$V"
printf '{\n  ".": "0.40.3"\n}\n' > "$DIR_D/.release-please-manifest.json"
run_scenario "D_stale_release_manifest" "$DIR_D" 1 "release-please-manifest"

# Scenario E — the real repository lock (Green and unchanged).
run_scenario "E_repository_green" "$REPO_ROOT" 0 "check-workspace-versions: OK"

printf '=== harness result: %d passed, %d failed ===\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ]
